<?php
/**
 * UserResourceApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Internetmarke
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deutsche Post INTERNETMARKE API
 *
 * Division: Post & Parcel Germany<br /> The INTERNETMARKE is the online-postage for mail products of Deutsche Post AG.
 *
 * The version of the OpenAPI document: 1.25
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Internetmarke\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\Internetmarke\ApiException;
use OpenAPI\Client\Internetmarke\Configuration;
use OpenAPI\Client\Internetmarke\HeaderSelector;
use OpenAPI\Client\Internetmarke\ObjectSerializer;

/**
 * UserResourceApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Internetmarke
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserResourceApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'authorization' => [
            'application/x-www-form-urlencoded',
        ],
        'retrieveUserData' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation authorization
     *
     * Get authorization token.
     *
     * @param  string $grantType OAuth2 standard content, must be set to &#39;client_credentials&#39; (required)
     * @param  string $username Internetmarke user name (e.g. &#39;franz.klammer&#39;). (required)
     * @param  string $password Internetmarke password (e.g. &#39;abfahrt123#&#39;) (required)
     * @param  string $clientId API client_id obtained from developer portal (e.g. &#39;XjSnyVWgQp1ShIQ5HQ6Vq5PIYLN2jGNS&#39;) (required)
     * @param  string $clientSecret API client_secret obtained from developer portal (e.g. &#39;TICgJWGRysH7mA57&#39;) (required)
     * @param  bool $forPayment Flag to indicate the authorization for payment use case. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authorization'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Internetmarke\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Internetmarke\Model\Authentication200Response|\OpenAPI\Client\Internetmarke\Model\RequestStatus|\OpenAPI\Client\Internetmarke\Model\Error401Response|\OpenAPI\Client\Internetmarke\Model\Error429Response|\OpenAPI\Client\Internetmarke\Model\RequestStatus
     */
    public function authorization($grantType, $username, $password, $clientId, $clientSecret, $forPayment = false, string $contentType = self::contentTypes['authorization'][0])
    {
        list($response) = $this->authorizationWithHttpInfo($grantType, $username, $password, $clientId, $clientSecret, $forPayment, $contentType);
        return $response;
    }

    /**
     * Operation authorizationWithHttpInfo
     *
     * Get authorization token.
     *
     * @param  string $grantType OAuth2 standard content, must be set to &#39;client_credentials&#39; (required)
     * @param  string $username Internetmarke user name (e.g. &#39;franz.klammer&#39;). (required)
     * @param  string $password Internetmarke password (e.g. &#39;abfahrt123#&#39;) (required)
     * @param  string $clientId API client_id obtained from developer portal (e.g. &#39;XjSnyVWgQp1ShIQ5HQ6Vq5PIYLN2jGNS&#39;) (required)
     * @param  string $clientSecret API client_secret obtained from developer portal (e.g. &#39;TICgJWGRysH7mA57&#39;) (required)
     * @param  bool $forPayment Flag to indicate the authorization for payment use case. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authorization'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Internetmarke\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Internetmarke\Model\Authentication200Response|\OpenAPI\Client\Internetmarke\Model\RequestStatus|\OpenAPI\Client\Internetmarke\Model\Error401Response|\OpenAPI\Client\Internetmarke\Model\Error429Response|\OpenAPI\Client\Internetmarke\Model\RequestStatus, HTTP status code, HTTP response headers (array of strings)
     */
    public function authorizationWithHttpInfo($grantType, $username, $password, $clientId, $clientSecret, $forPayment = false, string $contentType = self::contentTypes['authorization'][0])
    {
        $request = $this->authorizationRequest($grantType, $username, $password, $clientId, $clientSecret, $forPayment, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Internetmarke\Model\Authentication200Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Internetmarke\Model\Authentication200Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Internetmarke\Model\Authentication200Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\OpenAPI\Client\Internetmarke\Model\RequestStatus' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Internetmarke\Model\RequestStatus' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Internetmarke\Model\RequestStatus', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\OpenAPI\Client\Internetmarke\Model\Error401Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Internetmarke\Model\Error401Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Internetmarke\Model\Error401Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 429:
                    if ('\OpenAPI\Client\Internetmarke\Model\Error429Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Internetmarke\Model\Error429Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Internetmarke\Model\Error429Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\OpenAPI\Client\Internetmarke\Model\RequestStatus' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Internetmarke\Model\RequestStatus' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Internetmarke\Model\RequestStatus', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Internetmarke\Model\Authentication200Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Internetmarke\Model\Authentication200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Internetmarke\Model\RequestStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Internetmarke\Model\Error401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Internetmarke\Model\Error429Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Internetmarke\Model\RequestStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation authorizationAsync
     *
     * Get authorization token.
     *
     * @param  string $grantType OAuth2 standard content, must be set to &#39;client_credentials&#39; (required)
     * @param  string $username Internetmarke user name (e.g. &#39;franz.klammer&#39;). (required)
     * @param  string $password Internetmarke password (e.g. &#39;abfahrt123#&#39;) (required)
     * @param  string $clientId API client_id obtained from developer portal (e.g. &#39;XjSnyVWgQp1ShIQ5HQ6Vq5PIYLN2jGNS&#39;) (required)
     * @param  string $clientSecret API client_secret obtained from developer portal (e.g. &#39;TICgJWGRysH7mA57&#39;) (required)
     * @param  bool $forPayment Flag to indicate the authorization for payment use case. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authorization'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authorizationAsync($grantType, $username, $password, $clientId, $clientSecret, $forPayment = false, string $contentType = self::contentTypes['authorization'][0])
    {
        return $this->authorizationAsyncWithHttpInfo($grantType, $username, $password, $clientId, $clientSecret, $forPayment, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation authorizationAsyncWithHttpInfo
     *
     * Get authorization token.
     *
     * @param  string $grantType OAuth2 standard content, must be set to &#39;client_credentials&#39; (required)
     * @param  string $username Internetmarke user name (e.g. &#39;franz.klammer&#39;). (required)
     * @param  string $password Internetmarke password (e.g. &#39;abfahrt123#&#39;) (required)
     * @param  string $clientId API client_id obtained from developer portal (e.g. &#39;XjSnyVWgQp1ShIQ5HQ6Vq5PIYLN2jGNS&#39;) (required)
     * @param  string $clientSecret API client_secret obtained from developer portal (e.g. &#39;TICgJWGRysH7mA57&#39;) (required)
     * @param  bool $forPayment Flag to indicate the authorization for payment use case. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authorization'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authorizationAsyncWithHttpInfo($grantType, $username, $password, $clientId, $clientSecret, $forPayment = false, string $contentType = self::contentTypes['authorization'][0])
    {
        $returnType = '\OpenAPI\Client\Internetmarke\Model\Authentication200Response';
        $request = $this->authorizationRequest($grantType, $username, $password, $clientId, $clientSecret, $forPayment, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'authorization'
     *
     * @param  string $grantType OAuth2 standard content, must be set to &#39;client_credentials&#39; (required)
     * @param  string $username Internetmarke user name (e.g. &#39;franz.klammer&#39;). (required)
     * @param  string $password Internetmarke password (e.g. &#39;abfahrt123#&#39;) (required)
     * @param  string $clientId API client_id obtained from developer portal (e.g. &#39;XjSnyVWgQp1ShIQ5HQ6Vq5PIYLN2jGNS&#39;) (required)
     * @param  string $clientSecret API client_secret obtained from developer portal (e.g. &#39;TICgJWGRysH7mA57&#39;) (required)
     * @param  bool $forPayment Flag to indicate the authorization for payment use case. (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authorization'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function authorizationRequest($grantType, $username, $password, $clientId, $clientSecret, $forPayment = false, string $contentType = self::contentTypes['authorization'][0])
    {

        // verify the required parameter 'grantType' is set
        if ($grantType === null || (is_array($grantType) && count($grantType) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $grantType when calling authorization'
            );
        }

        // verify the required parameter 'username' is set
        if ($username === null || (is_array($username) && count($username) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $username when calling authorization'
            );
        }

        // verify the required parameter 'password' is set
        if ($password === null || (is_array($password) && count($password) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $password when calling authorization'
            );
        }

        // verify the required parameter 'clientId' is set
        if ($clientId === null || (is_array($clientId) && count($clientId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $clientId when calling authorization'
            );
        }

        // verify the required parameter 'clientSecret' is set
        if ($clientSecret === null || (is_array($clientSecret) && count($clientSecret) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $clientSecret when calling authorization'
            );
        }



        $resourcePath = '/user';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $forPayment,
            'forPayment', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);



        // form params
        if ($grantType !== null) {
            $formParams['grant_type'] = ObjectSerializer::toFormValue($grantType);
        }
        // form params
        if ($username !== null) {
            $formParams['username'] = ObjectSerializer::toFormValue($username);
        }
        // form params
        if ($password !== null) {
            $formParams['password'] = ObjectSerializer::toFormValue($password);
        }
        // form params
        if ($clientId !== null) {
            $formParams['client_id'] = ObjectSerializer::toFormValue($clientId);
        }
        // form params
        if ($clientSecret !== null) {
            $formParams['client_secret'] = ObjectSerializer::toFormValue($clientSecret);
        }

        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation retrieveUserData
     *
     * Authenticate and retrieve authorized user&#39;s data for shop.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['retrieveUserData'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Internetmarke\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Internetmarke\Model\RetrieveUserDataResponse|\OpenAPI\Client\Internetmarke\Model\RequestStatus|\OpenAPI\Client\Internetmarke\Model\Error401Response|\OpenAPI\Client\Internetmarke\Model\Error429Response|\OpenAPI\Client\Internetmarke\Model\RequestStatus
     */
    public function retrieveUserData(string $contentType = self::contentTypes['retrieveUserData'][0])
    {
        list($response) = $this->retrieveUserDataWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation retrieveUserDataWithHttpInfo
     *
     * Authenticate and retrieve authorized user&#39;s data for shop.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['retrieveUserData'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\Internetmarke\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Internetmarke\Model\RetrieveUserDataResponse|\OpenAPI\Client\Internetmarke\Model\RequestStatus|\OpenAPI\Client\Internetmarke\Model\Error401Response|\OpenAPI\Client\Internetmarke\Model\Error429Response|\OpenAPI\Client\Internetmarke\Model\RequestStatus, HTTP status code, HTTP response headers (array of strings)
     */
    public function retrieveUserDataWithHttpInfo(string $contentType = self::contentTypes['retrieveUserData'][0])
    {
        $request = $this->retrieveUserDataRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Internetmarke\Model\RetrieveUserDataResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Internetmarke\Model\RetrieveUserDataResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Internetmarke\Model\RetrieveUserDataResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\OpenAPI\Client\Internetmarke\Model\RequestStatus' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Internetmarke\Model\RequestStatus' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Internetmarke\Model\RequestStatus', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\OpenAPI\Client\Internetmarke\Model\Error401Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Internetmarke\Model\Error401Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Internetmarke\Model\Error401Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 429:
                    if ('\OpenAPI\Client\Internetmarke\Model\Error429Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Internetmarke\Model\Error429Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Internetmarke\Model\Error429Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\OpenAPI\Client\Internetmarke\Model\RequestStatus' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Internetmarke\Model\RequestStatus' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Internetmarke\Model\RequestStatus', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Internetmarke\Model\RetrieveUserDataResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Internetmarke\Model\RetrieveUserDataResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Internetmarke\Model\RequestStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Internetmarke\Model\Error401Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Internetmarke\Model\Error429Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Internetmarke\Model\RequestStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation retrieveUserDataAsync
     *
     * Authenticate and retrieve authorized user&#39;s data for shop.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['retrieveUserData'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function retrieveUserDataAsync(string $contentType = self::contentTypes['retrieveUserData'][0])
    {
        return $this->retrieveUserDataAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation retrieveUserDataAsyncWithHttpInfo
     *
     * Authenticate and retrieve authorized user&#39;s data for shop.
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['retrieveUserData'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function retrieveUserDataAsyncWithHttpInfo(string $contentType = self::contentTypes['retrieveUserData'][0])
    {
        $returnType = '\OpenAPI\Client\Internetmarke\Model\RetrieveUserDataResponse';
        $request = $this->retrieveUserDataRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'retrieveUserData'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['retrieveUserData'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function retrieveUserDataRequest(string $contentType = self::contentTypes['retrieveUserData'][0])
    {


        $resourcePath = '/user/profile';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
