<?php
/**
 * AppShoppingCartPosition
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Internetmarke
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deutsche Post INTERNETMARKE API
 *
 * Division: Post & Parcel Germany<br /> The INTERNETMARKE is the online-postage for mail products of Deutsche Post AG.
 *
 * The version of the OpenAPI document: 1.23
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Internetmarke\Model;

use \ArrayAccess;
use \OpenAPI\Client\Internetmarke\ObjectSerializer;

/**
 * AppShoppingCartPosition Class Doc Comment
 *
 * @category Class
 * @description The representation of an order item in PNG format.
 * @package  OpenAPI\Client\Internetmarke
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AppShoppingCartPosition implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = 'positionType';

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AppShoppingCartPosition';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'productCode' => 'int',
        'imageID' => 'int',
        'address' => '\OpenAPI\Client\Internetmarke\Model\AddressBinding',
        'additionalInfo' => 'string',
        'voucherLayout' => 'string',
        'cashOnDelivery' => '\OpenAPI\Client\Internetmarke\Model\CashOnDelivery',
        'positionType' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'productCode' => 'int32',
        'imageID' => 'int32',
        'address' => null,
        'additionalInfo' => null,
        'voucherLayout' => null,
        'cashOnDelivery' => null,
        'positionType' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'productCode' => false,
		'imageID' => false,
		'address' => false,
		'additionalInfo' => false,
		'voucherLayout' => false,
		'cashOnDelivery' => false,
		'positionType' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'productCode' => 'productCode',
        'imageID' => 'imageID',
        'address' => 'address',
        'additionalInfo' => 'additionalInfo',
        'voucherLayout' => 'voucherLayout',
        'cashOnDelivery' => 'cashOnDelivery',
        'positionType' => 'positionType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'productCode' => 'setProductCode',
        'imageID' => 'setImageID',
        'address' => 'setAddress',
        'additionalInfo' => 'setAdditionalInfo',
        'voucherLayout' => 'setVoucherLayout',
        'cashOnDelivery' => 'setCashOnDelivery',
        'positionType' => 'setPositionType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'productCode' => 'getProductCode',
        'imageID' => 'getImageID',
        'address' => 'getAddress',
        'additionalInfo' => 'getAdditionalInfo',
        'voucherLayout' => 'getVoucherLayout',
        'cashOnDelivery' => 'getCashOnDelivery',
        'positionType' => 'getPositionType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const VOUCHER_LAYOUT_ADDRESS_ZONE = 'ADDRESS_ZONE';
    public const VOUCHER_LAYOUT_FRANKING_ZONE = 'FRANKING_ZONE';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getVoucherLayoutAllowableValues()
    {
        return [
            self::VOUCHER_LAYOUT_ADDRESS_ZONE,
            self::VOUCHER_LAYOUT_FRANKING_ZONE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('productCode', $data ?? [], null);
        $this->setIfExists('imageID', $data ?? [], null);
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('additionalInfo', $data ?? [], null);
        $this->setIfExists('voucherLayout', $data ?? [], null);
        $this->setIfExists('cashOnDelivery', $data ?? [], null);
        $this->setIfExists('positionType', $data ?? [], null);

        // Initialize discriminator property with the model name.
        $this->container['positionType'] = static::$openAPIModelName;
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['productCode'] === null) {
            $invalidProperties[] = "'productCode' can't be null";
        }
        if (($this->container['productCode'] < 1)) {
            $invalidProperties[] = "invalid value for 'productCode', must be bigger than or equal to 1.";
        }

        if ($this->container['voucherLayout'] === null) {
            $invalidProperties[] = "'voucherLayout' can't be null";
        }
        $allowedValues = $this->getVoucherLayoutAllowableValues();
        if (!is_null($this->container['voucherLayout']) && !in_array($this->container['voucherLayout'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'voucherLayout', must be one of '%s'",
                $this->container['voucherLayout'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['positionType'] === null) {
            $invalidProperties[] = "'positionType' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets productCode
     *
     * @return int
     */
    public function getProductCode()
    {
        return $this->container['productCode'];
    }

    /**
     * Sets productCode
     *
     * @param int $productCode The internal product code for the selected product, e.g. standard letter, maxi letter etc. The product code must be greater than 0 and the product must be available in the third-party application.
     *
     * @return self
     */
    public function setProductCode($productCode)
    {
        if (is_null($productCode)) {
            throw new \InvalidArgumentException('non-nullable productCode cannot be null');
        }

        if (($productCode < 1)) {
            throw new \InvalidArgumentException('invalid value for $productCode when calling AppShoppingCartPosition., must be bigger than or equal to 1.');
        }

        $this->container['productCode'] = $productCode;

        return $this;
    }

    /**
     * Gets imageID
     *
     * @return int|null
     */
    public function getImageID()
    {
        return $this->container['imageID'];
    }

    /**
     * Sets imageID
     *
     * @param int|null $imageID The id of the motif to be printed.
     *
     * @return self
     */
    public function setImageID($imageID)
    {
        if (is_null($imageID)) {
            throw new \InvalidArgumentException('non-nullable imageID cannot be null');
        }
        $this->container['imageID'] = $imageID;

        return $this;
    }

    /**
     * Gets address
     *
     * @return \OpenAPI\Client\Internetmarke\Model\AddressBinding|null
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param \OpenAPI\Client\Internetmarke\Model\AddressBinding|null $address address
     *
     * @return self
     */
    public function setAddress($address)
    {
        if (is_null($address)) {
            throw new \InvalidArgumentException('non-nullable address cannot be null');
        }
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets additionalInfo
     *
     * @return string|null
     */
    public function getAdditionalInfo()
    {
        return $this->container['additionalInfo'];
    }

    /**
     * Sets additionalInfo
     *
     * @param string|null $additionalInfo Additional information on the order item.
     *
     * @return self
     */
    public function setAdditionalInfo($additionalInfo)
    {
        if (is_null($additionalInfo)) {
            throw new \InvalidArgumentException('non-nullable additionalInfo cannot be null');
        }
        $this->container['additionalInfo'] = $additionalInfo;

        return $this;
    }

    /**
     * Gets voucherLayout
     *
     * @return string
     */
    public function getVoucherLayout()
    {
        return $this->container['voucherLayout'];
    }

    /**
     * Sets voucherLayout
     *
     * @param string $voucherLayout voucherLayout
     *
     * @return self
     */
    public function setVoucherLayout($voucherLayout)
    {
        if (is_null($voucherLayout)) {
            throw new \InvalidArgumentException('non-nullable voucherLayout cannot be null');
        }
        $allowedValues = $this->getVoucherLayoutAllowableValues();
        if (!in_array($voucherLayout, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'voucherLayout', must be one of '%s'",
                    $voucherLayout,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['voucherLayout'] = $voucherLayout;

        return $this;
    }

    /**
     * Gets cashOnDelivery
     *
     * @return \OpenAPI\Client\Internetmarke\Model\CashOnDelivery|null
     */
    public function getCashOnDelivery()
    {
        return $this->container['cashOnDelivery'];
    }

    /**
     * Sets cashOnDelivery
     *
     * @param \OpenAPI\Client\Internetmarke\Model\CashOnDelivery|null $cashOnDelivery cashOnDelivery
     *
     * @return self
     */
    public function setCashOnDelivery($cashOnDelivery)
    {
        if (is_null($cashOnDelivery)) {
            throw new \InvalidArgumentException('non-nullable cashOnDelivery cannot be null');
        }
        $this->container['cashOnDelivery'] = $cashOnDelivery;

        return $this;
    }

    /**
     * Gets positionType
     *
     * @return string
     */
    public function getPositionType()
    {
        return $this->container['positionType'];
    }

    /**
     * Sets positionType
     *
     * @param string $positionType positionType
     *
     * @return self
     */
    public function setPositionType($positionType)
    {
        if (is_null($positionType)) {
            throw new \InvalidArgumentException('non-nullable positionType cannot be null');
        }
        $this->container['positionType'] = $positionType;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


