<?php
/**
 * PageFormat
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Internetmarke
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deutsche Post INTERNETMARKE API
 *
 * Division: Post & Parcel Germany<br /> The INTERNETMARKE is the online-postage for mail products of Deutsche Post AG.
 *
 * The version of the OpenAPI document: 1.25
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Internetmarke\Model;

use \ArrayAccess;
use \OpenAPI\Client\Internetmarke\ObjectSerializer;

/**
 * PageFormat Class Doc Comment
 *
 * @category Class
 * @description The representation of a page format.
 * @package  OpenAPI\Client\Internetmarke
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PageFormat implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PageFormat';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'isAddressPossible' => 'bool',
        'isImagePossible' => 'bool',
        'name' => 'string',
        'description' => 'string',
        'pageType' => 'string',
        'pageLayout' => '\OpenAPI\Client\Internetmarke\Model\PageLayout'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'int32',
        'isAddressPossible' => null,
        'isImagePossible' => null,
        'name' => null,
        'description' => null,
        'pageType' => null,
        'pageLayout' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
		'isAddressPossible' => false,
		'isImagePossible' => false,
		'name' => false,
		'description' => false,
		'pageType' => false,
		'pageLayout' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'isAddressPossible' => 'isAddressPossible',
        'isImagePossible' => 'isImagePossible',
        'name' => 'name',
        'description' => 'description',
        'pageType' => 'pageType',
        'pageLayout' => 'pageLayout'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'isAddressPossible' => 'setIsAddressPossible',
        'isImagePossible' => 'setIsImagePossible',
        'name' => 'setName',
        'description' => 'setDescription',
        'pageType' => 'setPageType',
        'pageLayout' => 'setPageLayout'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'isAddressPossible' => 'getIsAddressPossible',
        'isImagePossible' => 'getIsImagePossible',
        'name' => 'getName',
        'description' => 'getDescription',
        'pageType' => 'getPageType',
        'pageLayout' => 'getPageLayout'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PAGE_TYPE_REGULARPAGE = 'REGULARPAGE';
    public const PAGE_TYPE_ENVELOPE = 'ENVELOPE';
    public const PAGE_TYPE_LABELPRINTER = 'LABELPRINTER';
    public const PAGE_TYPE_LABELPAGE = 'LABELPAGE';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPageTypeAllowableValues()
    {
        return [
            self::PAGE_TYPE_REGULARPAGE,
            self::PAGE_TYPE_ENVELOPE,
            self::PAGE_TYPE_LABELPRINTER,
            self::PAGE_TYPE_LABELPAGE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('isAddressPossible', $data ?? [], null);
        $this->setIfExists('isImagePossible', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('pageType', $data ?? [], null);
        $this->setIfExists('pageLayout', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['pageType'] === null) {
            $invalidProperties[] = "'pageType' can't be null";
        }
        $allowedValues = $this->getPageTypeAllowableValues();
        if (!is_null($this->container['pageType']) && !in_array($this->container['pageType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'pageType', must be one of '%s'",
                $this->container['pageType'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['pageLayout'] === null) {
            $invalidProperties[] = "'pageLayout' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id The ID of the print format.
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets isAddressPossible
     *
     * @return bool|null
     */
    public function getIsAddressPossible()
    {
        return $this->container['isAddressPossible'];
    }

    /**
     * Sets isAddressPossible
     *
     * @param bool|null $isAddressPossible True, if addresses can be printed on the franking marks with the print format.
     *
     * @return self
     */
    public function setIsAddressPossible($isAddressPossible)
    {
        if (is_null($isAddressPossible)) {
            throw new \InvalidArgumentException('non-nullable isAddressPossible cannot be null');
        }
        $this->container['isAddressPossible'] = $isAddressPossible;

        return $this;
    }

    /**
     * Gets isImagePossible
     *
     * @return bool|null
     */
    public function getIsImagePossible()
    {
        return $this->container['isImagePossible'];
    }

    /**
     * Sets isImagePossible
     *
     * @param bool|null $isImagePossible True, if motifs can be printed on the franking marks with the print format.
     *
     * @return self
     */
    public function setIsImagePossible($isImagePossible)
    {
        if (is_null($isImagePossible)) {
            throw new \InvalidArgumentException('non-nullable isImagePossible cannot be null');
        }
        $this->container['isImagePossible'] = $isImagePossible;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The name of the print format, e.g. DIN A4 plain paper or letter C5 162 x 229.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description The description of the print format.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets pageType
     *
     * @return string
     */
    public function getPageType()
    {
        return $this->container['pageType'];
    }

    /**
     * Sets pageType
     *
     * @param string $pageType The specification of the print medium.)
     *
     * @return self
     */
    public function setPageType($pageType)
    {
        if (is_null($pageType)) {
            throw new \InvalidArgumentException('non-nullable pageType cannot be null');
        }
        $allowedValues = $this->getPageTypeAllowableValues();
        if (!in_array($pageType, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'pageType', must be one of '%s'",
                    $pageType,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['pageType'] = $pageType;

        return $this;
    }

    /**
     * Gets pageLayout
     *
     * @return \OpenAPI\Client\Internetmarke\Model\PageLayout
     */
    public function getPageLayout()
    {
        return $this->container['pageLayout'];
    }

    /**
     * Sets pageLayout
     *
     * @param \OpenAPI\Client\Internetmarke\Model\PageLayout $pageLayout pageLayout
     *
     * @return self
     */
    public function setPageLayout($pageLayout)
    {
        if (is_null($pageLayout)) {
            throw new \InvalidArgumentException('non-nullable pageLayout cannot be null');
        }
        $this->container['pageLayout'] = $pageLayout;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


