<?php
/**
 * RetrieveGalleryResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Internetmarke
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deutsche Post INTERNETMARKE API
 *
 * Division: Post & Parcel Germany<br /> The INTERNETMARKE is the online-postage for mail products of Deutsche Post AG.
 *
 * The version of the OpenAPI document: 1.23
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Internetmarke\Model;

use \ArrayAccess;
use \OpenAPI\Client\Internetmarke\ObjectSerializer;

/**
 * RetrieveGalleryResponse Class Doc Comment
 *
 * @category Class
 * @description Response object for the retrieved galleries.
 * @package  OpenAPI\Client\Internetmarke
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RetrieveGalleryResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RetrieveGalleryResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'privateGallery' => '\OpenAPI\Client\Internetmarke\Model\PrivateGallery',
        'publicGallery' => '\OpenAPI\Client\Internetmarke\Model\PublicGallery',
        'pageFormats' => '\OpenAPI\Client\Internetmarke\Model\PageFormat[]',
        'contractProducts' => '\OpenAPI\Client\Internetmarke\Model\ContractProducts'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'privateGallery' => null,
        'publicGallery' => null,
        'pageFormats' => null,
        'contractProducts' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'privateGallery' => false,
		'publicGallery' => false,
		'pageFormats' => false,
		'contractProducts' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'privateGallery' => 'privateGallery',
        'publicGallery' => 'publicGallery',
        'pageFormats' => 'pageFormats',
        'contractProducts' => 'contractProducts'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'privateGallery' => 'setPrivateGallery',
        'publicGallery' => 'setPublicGallery',
        'pageFormats' => 'setPageFormats',
        'contractProducts' => 'setContractProducts'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'privateGallery' => 'getPrivateGallery',
        'publicGallery' => 'getPublicGallery',
        'pageFormats' => 'getPageFormats',
        'contractProducts' => 'getContractProducts'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('privateGallery', $data ?? [], null);
        $this->setIfExists('publicGallery', $data ?? [], null);
        $this->setIfExists('pageFormats', $data ?? [], null);
        $this->setIfExists('contractProducts', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets privateGallery
     *
     * @return \OpenAPI\Client\Internetmarke\Model\PrivateGallery|null
     */
    public function getPrivateGallery()
    {
        return $this->container['privateGallery'];
    }

    /**
     * Sets privateGallery
     *
     * @param \OpenAPI\Client\Internetmarke\Model\PrivateGallery|null $privateGallery privateGallery
     *
     * @return self
     */
    public function setPrivateGallery($privateGallery)
    {
        if (is_null($privateGallery)) {
            throw new \InvalidArgumentException('non-nullable privateGallery cannot be null');
        }
        $this->container['privateGallery'] = $privateGallery;

        return $this;
    }

    /**
     * Gets publicGallery
     *
     * @return \OpenAPI\Client\Internetmarke\Model\PublicGallery|null
     */
    public function getPublicGallery()
    {
        return $this->container['publicGallery'];
    }

    /**
     * Sets publicGallery
     *
     * @param \OpenAPI\Client\Internetmarke\Model\PublicGallery|null $publicGallery publicGallery
     *
     * @return self
     */
    public function setPublicGallery($publicGallery)
    {
        if (is_null($publicGallery)) {
            throw new \InvalidArgumentException('non-nullable publicGallery cannot be null');
        }
        $this->container['publicGallery'] = $publicGallery;

        return $this;
    }

    /**
     * Gets pageFormats
     *
     * @return \OpenAPI\Client\Internetmarke\Model\PageFormat[]|null
     */
    public function getPageFormats()
    {
        return $this->container['pageFormats'];
    }

    /**
     * Sets pageFormats
     *
     * @param \OpenAPI\Client\Internetmarke\Model\PageFormat[]|null $pageFormats The container of page formats.
     *
     * @return self
     */
    public function setPageFormats($pageFormats)
    {
        if (is_null($pageFormats)) {
            throw new \InvalidArgumentException('non-nullable pageFormats cannot be null');
        }
        $this->container['pageFormats'] = $pageFormats;

        return $this;
    }

    /**
     * Gets contractProducts
     *
     * @return \OpenAPI\Client\Internetmarke\Model\ContractProducts|null
     */
    public function getContractProducts()
    {
        return $this->container['contractProducts'];
    }

    /**
     * Sets contractProducts
     *
     * @param \OpenAPI\Client\Internetmarke\Model\ContractProducts|null $contractProducts contractProducts
     *
     * @return self
     */
    public function setContractProducts($contractProducts)
    {
        if (is_null($contractProducts)) {
            throw new \InvalidArgumentException('non-nullable contractProducts cannot be null');
        }
        $this->container['contractProducts'] = $contractProducts;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


