<?php
/**
 * AppResourceApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client\Internetmarke
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Deutsche Post INTERNETMARKE API
 *
 * Division: Post & Parcel Germany<br /> The INTERNETMARKE is the online-postage for mail products of Deutsche Post AG.
 *
 * The version of the OpenAPI document: 1.23
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Internetmarke\Test\Api;

use \OpenAPI\Client\Internetmarke\Configuration;
use \OpenAPI\Client\Internetmarke\ApiException;
use \OpenAPI\Client\Internetmarke\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AppResourceApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client\Internetmarke
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AppResourceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for chargeWallet
     *
     * Charge users wallet.
     *
     */
    public function testChargeWallet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for checkoutShoppingCartPDFApp
     *
     * Checkouts ot the PDF shopping cart..
     *
     */
    public function testCheckoutShoppingCartPDFApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for checkoutShoppingCartPNGApp
     *
     * Checkouts ot the PNG shopping cart..
     *
     */
    public function testCheckoutShoppingCartPNGApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for initShoppingCartApp
     *
     * Initializes a shopping cart and returns the shopOrderId..
     *
     */
    public function testInitShoppingCartApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retoureVouchersApp
     *
     * Retoure vouchers For App..
     *
     */
    public function testRetoureVouchersApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retrieveGalleryApp
     *
     * Retrieve galleries..
     *
     */
    public function testRetrieveGalleryApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retrieveRetoureStateApp
     *
     * Retrieve retoure state for App..
     *
     */
    public function testRetrieveRetoureStateApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retrieveShoppingCartApp
     *
     * Retrieves a shopping cart..
     *
     */
    public function testRetrieveShoppingCartApp()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
